client_id       = "***************"
client_secret   = "***************"
tenant_id       = "***************"
subscription_id = "***************"
location        = "East US"
app_name        = "JenkinsToCloud"
